ALTER TABLE "carts" ALTER COLUMN "cart_item_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "coupons" ALTER COLUMN "coupon_redemption_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "inventory_adjustments" ALTER COLUMN "inventory_record_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "inventory_records" ALTER COLUMN "variant_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "notification_preferences" ALTER COLUMN "user_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "orders" ALTER COLUMN "vendor_order_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "orders" ALTER COLUMN "payment_transaction_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "orders" ALTER COLUMN "refund_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "orders" ALTER COLUMN "coupon_redemption_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "price_history_entries" ALTER COLUMN "product_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "price_history_entries" ALTER COLUMN "variant_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "product_variants" ALTER COLUMN "product_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "product_variants" ALTER COLUMN "cart_item_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "product_variants" ALTER COLUMN "line_item_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "products" ALTER COLUMN "vendor_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "products" ALTER COLUMN "review_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "products" ALTER COLUMN "wishlist_item_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "reviews" ALTER COLUMN "review_response_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "reviews" ALTER COLUMN "review_report_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "order_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "payment_method_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "coupon_redemption_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "review_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "wishlist_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "saved_search_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "refresh_token_family_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "verification_token_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "applicant_user_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "vendor_member_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "vendor_orders" ALTER COLUMN "line_item_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "vendor_orders" ALTER COLUMN "fulfillment_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "vendors" ALTER COLUMN "vendor_order_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "vendors" ALTER COLUMN "vendor_payout_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "vendors" ALTER COLUMN "review_response_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "vendors" ALTER COLUMN "vendor_application_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "vendors" ALTER COLUMN "vendor_member_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "vendors" ALTER COLUMN "operating_schedule_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "wishlists" ALTER COLUMN "wishlist_item_id" SET NOT NULL;